name: Docker Release

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build-push:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      - uses: actions/github-script@v3
        id: ref-sanitized
        with:
          script: |
            const ref = context.ref
            return ref.replace(/^refs\/heads\/|-/, '')

      - name: Login to dockerhub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.2.0
        with:
          images: |
            ghcr.io/zwave-js/zwavejs2mqtt
            zwavejs/zwavejs2mqtt
          tag-sha: true
          tag-latest: true
          tag-semver: |
            {{version}}
          label-custom: |
            org.opencontainers.image.vendor=zwave-js
            org.opencontainers.image.documentation=https://zwave-js.github.io/zwavejs2mqtt/#/
            org.opencontainers.image.authors=Daniel Lando <daniel.sorridi@gmail.com>
            org.opencontainers.image.url=https://zwave-js.github.io/zwavejs2mqtt/#/
            maintainer=robertsLando

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ steps.ref-sanitized.outputs.result }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ steps.ref-sanitized.outputs.result }}-${{ github.sha }}
            buildx-${{ steps.ref-sanitized.outputs.result }}
            buildx-

      - name: build+push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
          file: docker/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
